version: '2'
services:
    financeiro-app:
        image: financeiro
        external_links:
            - financeiro-mongodb:mongodb
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=financeiro
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    financeiro-mongodb:
        extends:
            file: mongodb.yml
            service: financeiro-mongodb
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
